## Example Exam Questions Chapter 4

## Exercise 1
Criminologists have long debated whether there is a relationship between weather conditions and the number of crimes committed. In 1988, an article “Is there a
Season for Homicide?” (Criminology, 1988: 287-296) classified 1361 homicides by season, resulting
in the data below.  
Is there an association between season and the number of murders committed?

In [2]:
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

In [3]:
dfmurders = pd.DataFrame(data={
    'season': ['winter', 'spring','summer','autumn'],
    'number_of_murders': [328, 334, 372, 327]
})

In [ ]:
Lab4.10
stap 1
goodness of fit test
ho en h1 bepalen
h0 = er is geen verband tussen de seizoen en het aantal moorden
h1= er is wel een verband tussen de seizoenen en het aantal moorden

stap 2
significance level alpha == 0.05

stap 3
test statistiek == chi²

In [5]:
alpha = 0.05
observed = dfmurders['number_of_murders']
expected_p = np.array ([0.25,0.25,0.25,0.25] )        # Significance level
n = sum(observed)          # Sample size
k = len(observed)          # Number of categories
dof = k - 1                # Degrees of freedom
expected = expected_p * n  # Expected absolute frequencies in the sample
g = stats.chi2.isf(alpha, df=dof)  # Critical value
chi2, p = stats.chisquare(f_obs=observed, f_exp=expected)
print(g,p,chi2)

7.814727903251178 0.25775920748891 4.034533431300514

## Exercise 2
A random sample of individuals was taken, and each individual was classified according to their level of education and their sense of spirituality.
Is there an association between the level of education and the sense of spirituality?

In [6]:
dfspirituality = pd.DataFrame(data={
    'sense_of_spirituality': ['lot', 'moderate','little','none'],
    'alfa_scientist': [56, 162, 198, 211],
    'beta_scientist': [56, 223, 243, 239],
    'not_scientist': [109, 164, 74, 28]
})
dfspirituality.head()

  sense_of_spirituality  alfa_scientist  beta_scientist  not_scientist
0                   lot              56              56            109
1              moderate             162             223            164
2                little             198             243             74
3                  none             211             239             28

In [ ]:
stap 1
h0 er is geen verband tussen type opleiding en spiritualiteit
h1 er is wel een verband
stap2
significance level
stap3
alpha 0.05
stap4

In [7]:
alpha=0.05
dfspirituality = dfspirituality.drop('sense_of_spirituality',axis=1)
chi2, p, dof, expected = stats.chi2_contingency(dfspirituality)
g = stats.chi2.isf(alpha, df=dof)

print("chi-squared            : %.4f" % chi2)
print("p-value                : %.4f" % p)
print("degrees of freedom     : %d" % dof)

chi-squared            : 213.2122
p-value                : 0.0000
degrees of freedom     : 6

## Exercise 4

In an experiment, 150 patients were divided into three groups of 45, 45 and 60 patients each. Two groups were given a new drug in different doses and the third group was given a placebo. The way the patients felt after using the drug are shown in the data frame below. Is there evidence at the 5% significance level that there is a difference in the condition between the three groups of patients?

In [8]:
dfexperiment = pd.DataFrame(data={
    'state': ['better', 'equal', 'worse'],
    'placebo': [16, 20, 9],
    'half_dosis': [17, 18, 10],
    'full_dosis': [26, 20, 14]
}).set_index('state')
dfexperiment.head()

        placebo  half_dosis  full_dosis
state
better       16          17          26
equal        20          18          20
worse         9          10          14

In [ ]:
oefening 4
stap 1
chi² test
h0 geen verband tss de gekregen dosis en de state
h1 er is wel een verband

In [9]:
chi2, p, df, expected = stats.chi2_contingency(dfexperiment)
g= stats.chi2.isf(0.05,df=df )

print("Chi-squared       : %.4f" % chi2)
print("Degrees of freedom: %d" % df)
print("P-value           : %.4f" % p)
print("g-value           : %.4f" % g)

Chi-squared       : 1.4169
Degrees of freedom: 4
P-value           : 0.8412
g-value           : 9.4877

In [ ]:
stap 4
chi² = 1.4 << g = 9.48 + p = 84% >> alpha 5%

er is niet voldoende aanwijzing om h0 te verwerpen
er is geen verband tussen de toegediende dosis en conditie